name: dadi
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - jupyterlab_widgets
  - ipywidgets
  - snakemake-minimal
  - numpy
  - scipy
  - dask
  - dadi
  - pip
  - pip:
    - nlopt
    - matplotlib
    - dask-labextension
